In [1]:
import pandas as pd
data = pd.read_csv('iris.csv') 
data = data.drop('Id',axis = 1)
data

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
x = data.drop('Species',axis = 1)
x.head(5)
data.head(5)

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
y = data['Species']
y.head(5)

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [5]:
#cross val import kiriima

from sklearn.model_selection import cross_val_score

In [6]:
#K-Nearest Neighbors

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
cross_val_score(knn,x,y,cv = 5).mean()

# ihatha cv = 5 vyannen wenne data tika piliwelata kotas 5 kata kadagena eewa wena wenama test and train lesa gena accuracy values 5 labee.
# pasuma .mean() magin ema labena accuracy values 5 he avaerage eka ganii

np.float64(0.9733333333333334)

In [7]:
#Random Forest

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
cross_val_score(rf,x,y,cv = 5).mean()

np.float64(0.96)

In [9]:
#Naive Bayes

from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
cross_val_score(nb,x,y,cv = 5).mean()

np.float64(0.9533333333333334)

In [15]:
#Support Vector Machine

from sklearn.svm import SVC
svm = SVC()
cross_val_score(svm,x,y,cv = 5).mean()

np.float64(0.9666666666666666)